//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.296
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturas {
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FacturasRecursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FacturasRecursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Facturas.FacturasRecursos", typeof(FacturasRecursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AdobeAcrobat {
            get {
                object obj = ResourceManager.GetObject("AdobeAcrobat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BindingNavigatorSkin_Delete {
            get {
                object obj = ResourceManager.GetObject("BindingNavigatorSkin_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon config {
            get {
                object obj = ResourceManager.GetObject("config", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existen datos sin guardar, ¿Deseas salir?.
        /// </summary>
        internal static string Configuracion_Configuracion_FormClosing_ {
            get {
                return ResourceManager.GetString("Configuracion_Configuracion_FormClosing_", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_add {
            get {
                object obj = ResourceManager.GetObject("document_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap explorar {
            get {
                object obj = ResourceManager.GetObject("explorar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap first_img {
            get {
                object obj = ResourceManager.GetObject("first_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione los datos del cliente.
        /// </summary>
        internal static string Form1_cargarDatosClienteToolStripMenuItem_Click_Seleccione_los_datos_del_cliente {
            get {
                return ResourceManager.GetString("Form1_cargarDatosClienteToolStripMenuItem_Click_Seleccione_los_datos_del_cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificado Digital (*.p12)|*.p12.
        /// </summary>
        internal static string Form1_firmarFacturaToolStripMenuItem_Click_Certificado_Digital____p12____p12 {
            get {
                return ResourceManager.GetString("Form1_firmarFacturaToolStripMenuItem_Click_Certificado_Digital____p12____p12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factura (*.pdf)|*.pdf.
        /// </summary>
        internal static string Form1_firmarFacturaToolStripMenuItem_Click_Factura____pdf____pdf {
            get {
                return ResourceManager.GetString("Form1_firmarFacturaToolStripMenuItem_Click_Factura____pdf____pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Factura Firmada como....
        /// </summary>
        internal static string Form1_firmarFacturaToolStripMenuItem_Click_Guardar_Factura_Firmada_como___ {
            get {
                return ResourceManager.GetString("Form1_firmarFacturaToolStripMenuItem_Click_Guardar_Factura_Firmada_como___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione su certificado de usuario.
        /// </summary>
        internal static string Form1_firmarFacturaToolStripMenuItem_Click_Seleccione_su_certificado_de_usuario {
            get {
                return ResourceManager.GetString("Form1_firmarFacturaToolStripMenuItem_Click_Seleccione_su_certificado_de_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una factura sin firmar.
        /// </summary>
        internal static string Form1_firmarFacturaToolStripMenuItem_Click_Seleccione_una_factura_sin_firmar {
            get {
                return ResourceManager.GetString("Form1_firmarFacturaToolStripMenuItem_Click_Seleccione_una_factura_sin_firmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factura (*.upo)|*.upo.
        /// </summary>
        internal static string Form1_guardarDatosClienteToolStripMenuItem_Click_Factura____upo____upo {
            get {
                return ResourceManager.GetString("Form1_guardarDatosClienteToolStripMenuItem_Click_Factura____upo____upo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Datos Cliente como....
        /// </summary>
        internal static string Form1_guardarDatosClienteToolStripMenuItem_Click_Guardar_Datos_Cliente_como___ {
            get {
                return ResourceManager.GetString("Form1_guardarDatosClienteToolStripMenuItem_Click_Guardar_Datos_Cliente_como___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factura (*.taxi)|*.taxi.
        /// </summary>
        internal static string Form1_guardarFacturaToolStripMenuItem_Click_Factura____taxi____taxi {
            get {
                return ResourceManager.GetString("Form1_guardarFacturaToolStripMenuItem_Click_Factura____taxi____taxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Factura como....
        /// </summary>
        internal static string Form1_guardarFacturaToolStripMenuItem_Click_Guardar_Factura_como___ {
            get {
                return ResourceManager.GetString("Form1_guardarFacturaToolStripMenuItem_Click_Guardar_Factura_como___", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap group_add {
            get {
                object obj = ResourceManager.GetObject("group_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_config {
            get {
                object obj = ResourceManager.GetObject("icon_config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap last_img {
            get {
                object obj = ResourceManager.GetObject("last_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lin_agt_wrench {
            get {
                object obj = ResourceManager.GetObject("lin_agt_wrench", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap next {
            get {
                object obj = ResourceManager.GetObject("next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nuevo {
            get {
                object obj = ResourceManager.GetObject("nuevo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap page {
            get {
                object obj = ResourceManager.GetObject("page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap prev {
            get {
                object obj = ResourceManager.GetObject("prev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sign {
            get {
                object obj = ResourceManager.GetObject("sign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sout {
            get {
                object obj = ResourceManager.GetObject("sout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Validar {
            get {
                object obj = ResourceManager.GetObject("Validar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
